### ISSUE TITLE
Quarter Project - Setup

### ISSUE THREAD

**Issue by DZ1987** [DZ1987/QuarterProject#1]
Quarter Project - Setup
- [ ] Change Project Name
- [ ] Change Repository Name
- [ ] Add Branch Protection Rules to the Project
- [ ] Update Project Target Framework to .NET 8.0
- [ ] Update NuGet Packages
- [ ] Add a README to the GitHub Repository
- [ ] Modify the layout of the Website
- [ ] Add some styling to the Website
- [ ] Add Create page for the Website
- [ ] Add Retrieve page for the Website
- [ ] Add Update page for the Website
- [ ] Add Delete page for the Website
- [ ] Create a Database for the Website
- [ ] Add some Seed Data to Database
